  - include: validate.yml
    tags:
      - kubernetes-setup

  - name: Install kubernetes using kubeadmn
    include: "{{ ansible_os_family | lower }}/main.yml"
    when: kubeadm_cmd_exists | failed
    tags:
      - kubernetes-setup
       
  - name: Initialize a kubernetes cluster
    command: kubeadm init
    when: kubernetes_cluster_exists | failed
    tags:
      - kubernetes-setup
      
# pods are not scheduled on the master by default for security reasons,to schedule the pods on the master run 'kubectl --kubeconfig ./admin.conf taint nodes --all node-role.kubernetes.io/master-'
# it used when we run one single node per cluster

  - name: Schedule pods on the master
    command: kubectl --kubeconfig ./admin.conf taint nodes --all node-role.kubernetes.io/master-
    tags:
      - kubernetes-setup

  - name: deploy network pod
    command: kubectl --kubeconfig ./admin.conf apply -f https://git.io/weave-kube

  - name: Deploy addons pods
    include: "addons/addons_deployment.yml"
    tags:
      - kubernetes-config
