- name: stop kubelet service
  service:
    name: kubelet
    state: stopped
- name: start kubelet service
  service:
    name: kubelet
    enabled: yes
    state: started
- name: start docker service
  service:
    name: docker
    enabled: yes
    state: started
- name: update grub
  shell: update-grub2
  
- name: disable swap
  shell: 
  
- name: deploy network pod
  command: kubectl apply -f https://git.io/weave-kube
