  - name : Install dependencies
    apt: 
     name: apt-transport-https
     state: installed

  - name: Debian | Add GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Debian | Add kubernetes repository
    apt_repository:  
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: "{{ kubernetes_debian_repository_filename }}"
      
  - name: Debian | Install kubeadm and dependencies 
    apt:
     name: "{{ item }}"
     state: installed
     update_cache: yes
    with_items:
      - docker.io
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni
    notify: 
      - stop kubelet service
      - start kubelet service
  - name: Debian | Enable cgroup 
    lineinfile:
     dest: /etc/default/grub
     regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="quiet'
     line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet cgroup_enable=memory"'
     state: present
     create: yes
    notify:
      - update grub
      
  - name: Debian | Disable swap
    shell: swapoff -a
    notify:
       - reload systemd
       - restart kubelet service 
